# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(auto_created=1, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=10240)),
                ('like', models.IntegerField()),
                ('unlike', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(auto_created=1, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10240)),
                ('username', models.CharField(max_length=32)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
