# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dataTime',
            field=models.DateTimeField(default=b'2017-06-26 01:24:28'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
