# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170626_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.IntegerField(auto_created=1, default=0, primary_key=True, serialize=False)),
                ('view', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.DateTimeField(default=b'2017-06-28 17:49:28'),
        ),
    ]
