# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170628_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.DateTimeField(default=b'2017-06-30 00:41:28'),
        ),
    ]
