# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170630_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.IntegerField(auto_created=1, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dataTime',
            field=models.DateTimeField(default=b'2017-06-30 17:48:37'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.IntegerField(auto_created=1, default=0, primary_key=True, serialize=False),
        ),
    ]
